### ISSUE TITLE
US 02.02.01 -  Add Ingredient to Recipe

### ISSUE THREAD

**Issue by Sehbazz-Virk** [CMPUT301F22T19/DietScoop#16]
As a meal planner, I want to add an ingredient to a recipe, with a brief description, amount, unit, and ingredient category.

**Comment by gurbirsandha** [comment]
### Acceptance criteria

- when editing a recipe, an "add ingredient" button should open a dialog to allow user to enter details of ingredient being added
- add to UML
- add to storyboard

**Comment by ksharma-2** [comment]
Viewing recipe details will have an "Add" button that opens a fragment where the user is able to enter details about the ingredient specific to that recipe.
