### ISSUE TITLE
US 02.03.01 - Delete ingredient from recipe

### ISSUE THREAD

**Issue by Sehbazz-Virk** [CMPUT301F22T19/DietScoop#19]
As a meal planner, I want to delete an ingredient from a recipe.

**Comment by gurbirsandha** [comment]
### Acceptance criteria

- when editing details of a recipe, a delete button or a slide-to-delete feature allows user to delete ingredient from recipe
- -add to UML diagram
- add to storyboard

**Comment by ksharma-2** [comment]
Clicking on a recipe in the RecyclerView, will automatically delete it from the recipe.

**Comment by Sehbazz-Virk** [comment]
Do you mean clicking on an ingredient?
