### ISSUE TITLE
US 01.06.01 - Sort Ingredients

### ISSUE THREAD

**Issue by gurbirsandha** [CMPUT301F22T19/DietScoop#2]
As a meal planner, I want to sort the list of ingredients by description, best before date, location, and ingredient category.

On the list of ingredients page:

add a sort button which opens a fragment that lets the user select which of the properties to sort by
    * description
    * prep time
    * num servings
    * recipe category
Selecting a property will close the fragment and sort the ingredient list.

**Comment by Sehbazz-Virk** [comment]
Complete!
