### ISSUE TITLE
US 02.05.01 - Edit recipe details

### ISSUE THREAD

**Issue by ksharma-2** [CMPUT301F22T19/DietScoop#20]
As a meal planner, I want to edit the details of a recipe, including the ingredients.

**Comment by gurbirsandha** [comment]
### Acceptance Criteria

- clicking an recipe opens a dialog showing current details and allows user to edit details
- add to UML diagram
- add to storyboard

**Comment by Sehbazz-Virk** [comment]
In Progress, bug where editing just creates a new recipe.
