### ISSUE TITLE
US 04.04.01 - Select Picked Up

### ISSUE THREAD

**Issue by ksharma-2** [CMPUT301F22T19/DietScoop#5]
As a meal planner, I want to note that I have picked up an ingredient on the shopping list.

### Acceptance Criteria

Clicking the ingredient in the shopping list will open a fragment as specified in issue #7 
This fragment should have a selection Button (or similar interface) to select if the item has been picked up
If an item has been picked up what do we do? remove it from shopping list or should that be a separate issue?

**Comment by Sehbazz-Virk** [comment]
Ask Jakaria/Prof about what to do when user selects "picked up"
