### ISSUE TITLE
US 03.02.01 - Scale Meal Plan

### ISSUE THREAD

**Issue by Sehbazz-Virk** [CMPUT301F22T19/DietScoop#6]
As a meal planner, I want to scale my recipes to adjust the number of servings for the meal plan.

### Acceptance criteria

* have a slider/spinner to select servings from 1-10 when adding recipes to the meal plan
* More details will be given about this issue when we flesh out the meal planning issue #14

**Comment by Marcos-GonzalezMayedo** [comment]
MealPlan has been scaled to multiple days. Main implementation and functionality is done.
